name: scanner_personal
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:


    sdk: flutter


  cupertino_icons: ^1.0.8
  file_picker: ^10.1.2
  supabase_flutter: ^2.8.4
  audioplayers: ^6.5.1
  http: ^1.5.0
  google_fonts: ^6.3.2
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  shared_preferences: ^2.2.2
  bcrypt: ^1.1.3
  logger: ^2.6.2
  flutter_dotenv: ^6.0.0
  rxdart: ^0.28.0
  record: ^6.1.2 # Reemplazar audio_recorder
  just_audio: ^0.10.0 # Para reproducción
  universal_io: ^2.2.2
  flutter_js: ^0.8.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  assets:
    - .env
    - assets/logoM.png

  uses-material-design: true
